### PR TITLE
Remove unnecessary update

### PR DESCRIPTION
**Pull request by alexpott**
Should prevent false pushes to drupal.org

### CODE REVIEW

**Comment by greggles** [comment]
:+1:

**Comment by jonpugh** [comment]
This is wrong, it would prevent drupal.org code from being mirrored to github.   

This console command, "hubdrop:update:all" is only used for mirrors whose "source" is drupal:  Pulled *from* drupal.org, then *pushed* to github. The "hubdrop:update:all" command runs continuously to ensure github.com is as up to date as possible. It only exists because there are no post commit hooks for drupal.org.

Hubdrop's "Project" class has a `source` variable, that is either "drupal" or "github".

It loops through every repo found at /var/hubdrop/repos, then runs $project->update().  This method just runs git pull  then git push.  The source for git is stored in the .git/config file.

So, when the project is loaded, the code now checks to see if the source is github.  If the source is github (to be pushed to drupal.org), we don't need to update, because those repos are updated on push to github via webhook.

So my fix is valid.  Now, the only time hubdrop will ever push to drupal.org is when it receives a push from a module maintainer to github.

Thank you for your contribution, though, and I hope this doesn't stop you from continuing to help!!

**Comment by jonpugh** [comment]
OH MAN. I have been working too hard.

**Comment by jonpugh** [comment]
I am really sorry, I did not read the code fully. I didn't realize I left the extra one in there.

I've been putting in really long hours these days.  

Please keep helping!

**Comment by jonpugh** [comment]
I've deployed the update to hubdrop.org.

THANKS!

**Comment by greggles** [comment]
BTW, when you read data from d.o are you using the http:// or the git:// repository format? Because I believe you can do http:// which should reduce the load on the git twisted daemon.

**Pull request merged**
